apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfgdfg-prod
  labels:
    environment-id: env_7a3789a7-9a98-48a4-88d9-61242fab814e
    project-id: project_7340ebd9-2e83-4b53-ae8d-4bab6c0966ce
    project-name: dfgdfgdfg
    environment-name: prod
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
